### ISSUE TITLE
'show config diff' failed with panos_op

### ISSUE THREAD

**Issue by ssk247net** [PaloAltoNetworks/pan-os-ansible#101]
## Describe the bug

'show config diff' with pano_op does not execute. This command fails to run.
Thank you for your assistance.

My playbook is as follows:

```
---
- name: show uncommitted changes
  hosts: pan
  gather_facts: False
  vars:
    provider:
      ip_address: x.x.x.x
      username: '******'
      password: '******'
  collections:
    - paloaltonetworks.panos

  tasks:
  - name: show uncommitted changes
    panos_op:
      provider: "{{ provider }}"
      cmd: "show config diff"
    register: config_diff

  - name: print system info
    debug:
      msg: "{{ config_diff.stdout }}"
```

## Expected behaviour

```
pandevice> show config diff 

+    address {
+      test_1234 {
+        ip-netmask 1.2.3.4/32;
+      }
+    }
   }

```
## Current behaviour

```
TASK [show uncommitted changes] *******************************************************************************************************************************************************************************************
fatal: [pan1]: FAILED! => {"changed": false, "msg": "Failed to run command : show config \"diff\" :  show -> config  is unexpected"}
```

## Your Environment

- Version used:
   Control node: Centos 7.8.2003 (on Azure)
   Ansible version: 2.9.6
   Python version: 3.6.9
   Palo Alto version: 
   - model: PA-VM
   - vm-mode: Microsoft Azure
   - cloud-mode: cloud
   - sw-version: 10.0.0
   - device-dictionary-version: 6-229
   - logdb-version: 10.0.1
   - vm_series: vm_series-2.0.0

**Comment by mrichardson03** [comment]
`panos_op` only supports commands that can be called via the API (see the API browser at https://<fw_ip>/api/).

A workaround could be to run `show config running` and `show config candidate`, and perform the diff on the control node.
