### ISSUE TITLE
Support additional tag colors

### ISSUE THREAD

**Issue by mrichardson03** [PaloAltoNetworks/pan-os-ansible#111]
PAN-OS 8.1 (maybe earlier) added additional tag colors.  Can add when pan-os-python support is merged: https://github.com/PaloAltoNetworks/pan-os-python/pull/267

**Comment by Rashmi0986** [comment]
Hi Richard is there any  documents or Pointers available to  figure out what all  the list of colors and  tags supported by PAN OS device?  

pls confirm . New to this code repo  would like to start off with simple bug fix .

**Comment by mrichardson03** [comment]
There's nothing to do.  The patch has been submitted to the upstream library, it just needs to be incorporated into a release.

**Comment by Rashmi0986** [comment]
Sure thanks Michael .

COuld you pls help me get started with the pan-os-ansible modules .

is there any easy bug i can pick up to get started .

I am new bee to this repo need some help identify the bug to get started .


Thanks and regards
RASHMI BS
