### ISSUE TITLE
Route lookup (to find zone)

### ISSUE THREAD

**Issue by ishuguru** [PaloAltoNetworks/pan-os-ansible#113]
As far as I understand this needs to be done with a op command now and needs to be parsed manualy. It would be good with a module for this. Otherwise trying to use ansible for creating policys in a firewall with lots of different zones is quite hard (since you need to check zones for all vlans)

A bonus would be if it would be possible to loop through lots of devices with the help of panorama to make it easier to also automate the creating of the policy in case of multiple firewalls

**Comment by mrichardson03** [comment]
This would need to come as a contribution.
