### ISSUE TITLE
Creation of panos_log or other appropriate name

### ISSUE THREAD

**Issue by jvanderaa** [PaloAltoNetworks/pan-os-ansible#128]
### Is your feature request related to a problem?

Would like to get show log output via Ansible

### Describe the solution you'd like

Would like to be able to get traffic log information via Ansible

### Describe alternatives you've considered

Attempted use of panos_op, but that fails

### Additional context

Looking to check historic logs for particular messages.

**Comment by mrichardson03** [comment]
Can you elaborate more on the use case?  Exporting logs via the API is possible, but it's fairly heavy on the management plane of the device.  It's almost always better to forward the logs via syslog or some other mechanism and look at historical logs there.

**Comment by jvanderaa** [comment]
The first particular use case was to gather operational logs to handle via Tower via a Survey. Then present a result back of rejected/permitted. Using URI for the task is quite intensive at the moment. But Ansible is the method that is going to be used to gather information and present back while keeping with the minimal touch points (network vs another team and have to worry about life cycle of the other tools).

**Comment by mrichardson03** [comment]
If that’s the goal, there actually is a better fit.  There’s a ‘test security-policy-match’ API command that will return if traffic from a particular source and destination is allowed by the security policy.  I was actually thinking of building that into a module anyway.

**Comment by mrichardson03** [comment]
I've committed support for `panos_security_rule_facts` to lookup security rules matching specific traffic.  This could be good for users to check if the firewall is blocking specific traffic, or as a first step in a rule change request workflow where you check to see if a change to allow the requested traffic is needed or not.
