### ISSUE TITLE
panos_facts interfaces fails on IPv6

### ISSUE THREAD

**Issue by patrickdaj** [PaloAltoNetworks/pan-os-ansible#13]
The panos_facts module tries to pull the "name" out of the IPv6Address objects but there is no name, only "address".  So, if panos_facts is run with gather_subset: ['interfaces'] it fails on name attribute.

## Expected behavior
panos_facts module with gather_subset: ['interfaces'] should not fail on IPv6 as there is built in support in the module.

## Current behavior
The module fails either with the default gather_subset of ['!config'] or gather_subset: ['interfaces'].

## Possible solution
I played with changing the following:

line 346 - iface_info['ipv6'].append(child.name)
to
iface_info['ipv6'].append(child.address)

and it appeared to fix the issue.

## Steps to reproduce

Use panos_facts module with following:

panos_facts:
  provider: '{{ provider }}'
  gather_subset: ['interfaces']

Ensure an IPv6 address is assigned to one of the interfaces

## Screenshots
I don't have any as I have limitations on what I can transfer from work computers etc.

## Context
It is consistent and I have had the problem both by manually configured IPv6 addresses as well as address objects in that field.

## Your Environment
PanOS 8.1.12 is my current setup
Galaxy role version 2.4.1
Pandevice version 0.14.0

**Comment by shinmog** [comment]
@patrickdaj 

Thanks for the debug work, I'll fix this.
