### ISSUE TITLE
Unable to set a default value for zone_profile, include_acl and exclude_acl when creating a zone.

### ISSUE THREAD

**Issue by SudarshanVK** [PaloAltoNetworks/pan-os-ansible#131]
## Describe the bug

Unable to set a default value for zone_profile, include_acl and exclude_acl when creating a zone.

## Expected behavior

Expect that the module will accept a default value of null for zone_profile, include_acl and exclude_acl as that is the value when extracting the zone facts.

## Current behavior

Here is a complete traceback of the error.

╰─ ❯ ansible-playbook configure_panos.yml -vvv
ansible-playbook 2.9.6
  config file = /Users/sudarshanv/Documents/Projects/panos-new/ansible.cfg
  configured module search path = ['/Users/sudarshanv/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/sudarshanv/Documents/virtualenvs/panos2.0.0/lib/python3.7/site-packages/ansible
  executable location = /Users/sudarshanv/Documents/virtualenvs/panos2.0.0/bin/ansible-playbook
  python version = 3.7.4 (v3.7.4:e09359112e, Jul  8 2019, 14:54:52) [Clang 6.0 (clang-600.0.57)]
Using /Users/sudarshanv/Documents/Projects/panos-new/ansible.cfg as config file
host_list declined parsing /Users/sudarshanv/Documents/Projects/panos-new/inventory.ini as it did not pass its verify_file() method
script declined parsing /Users/sudarshanv/Documents/Projects/panos-new/inventory.ini as it did not pass its verify_file() method
auto declined parsing /Users/sudarshanv/Documents/Projects/panos-new/inventory.ini as it did not pass its verify_file() method
yaml declined parsing /Users/sudarshanv/Documents/Projects/panos-new/inventory.ini as it did not pass its verify_file() method
Parsed /Users/sudarshanv/Documents/Projects/panos-new/inventory.ini inventory source with ini plugin

PLAYBOOK: configure_panos.yml *********************************************************************************************************************
1 plays in configure_panos.yml

PLAY [Panos Test] *********************************************************************************************************************************
META: ran handlers

TASK [IMPORT ==> CONFIGURATION FILE] **************************************************************************************************************
task path: /Users/sudarshanv/Documents/Projects/panos-new/configure_panos.yml:22
<192.168.1.135> ESTABLISH LOCAL CONNECTION FOR USER: sudarshanv
<192.168.1.135> EXEC /bin/sh -c 'echo ~sudarshanv && sleep 0'
<192.168.1.135> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/sudarshanv/.ansible/tmp/ansible-tmp-1600984672.279409-114414600949752 `" && echo ansible-tmp-1600984672.279409-114414600949752="` echo /Users/sudarshanv/.ansible/tmp/ansible-tmp-1600984672.279409-114414600949752 `" ) && sleep 0'
Using module file /Users/sudarshanv/Documents/Projects/panos-new/library/xls_to_facts.py
<192.168.1.135> PUT /Users/sudarshanv/.ansible/tmp/ansible-local-580937dyuoig_/tmpap3hzpkj TO /Users/sudarshanv/.ansible/tmp/ansible-tmp-1600984672.279409-114414600949752/AnsiballZ_xls_to_facts.py
<192.168.1.135> EXEC /bin/sh -c 'chmod u+x /Users/sudarshanv/.ansible/tmp/ansible-tmp-1600984672.279409-114414600949752/ /Users/sudarshanv/.ansible/tmp/ansible-tmp-1600984672.279409-114414600949752/AnsiballZ_xls_to_facts.py && sleep 0'
<192.168.1.135> EXEC /bin/sh -c '/Users/sudarshanv/Documents/virtualenvs/panos2.0.0/bin/python /Users/sudarshanv/.ansible/tmp/ansible-tmp-1600984672.279409-114414600949752/AnsiballZ_xls_to_facts.py && sleep 0'
<192.168.1.135> EXEC /bin/sh -c 'rm -f -r /Users/sudarshanv/.ansible/tmp/ansible-tmp-1600984672.279409-114414600949752/ > /dev/null 2>&1 && sleep 0'
ok: [pw-firewall] => {
    "ansible_facts": {
        "spreadsheet_Sheet2": [],
        "spreadsheet_zone": [
            {
                "Log Setting": null,
                "Name": "ansible1",
                "Template": "ansible_test",
                "Type": "layer3",
                "User ID Enabled": null,
                "Zone Protection Profile": null
            }
        ]
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "attributes": null,
            "backup": null,
            "content": null,
            "delimiter": null,
            "directory_mode": null,
            "follow": false,
            "force": null,
            "group": null,
            "mode": null,
            "owner": null,
            "regexp": null,
            "remote_src": null,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": "source.xlsx",
            "unsafe_writes": null
        }
    }
}

TASK [PANORAMA ==> CONFIGURE ZONE] ****************************************************************************************************************
task path: /Users/sudarshanv/Documents/Projects/panos-new/configure_panos.yml:27
<192.168.1.135> ESTABLISH LOCAL CONNECTION FOR USER: sudarshanv
<192.168.1.135> EXEC /bin/sh -c 'echo ~sudarshanv && sleep 0'
<192.168.1.135> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/sudarshanv/.ansible/tmp/ansible-tmp-1600984672.921371-61545073908576 `" && echo ansible-tmp-1600984672.921371-61545073908576="` echo /Users/sudarshanv/.ansible/tmp/ansible-tmp-1600984672.921371-61545073908576 `" ) && sleep 0'
Using module file /Users/sudarshanv/.ansible/collections/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_zone.py
<192.168.1.135> PUT /Users/sudarshanv/.ansible/tmp/ansible-local-580937dyuoig_/tmp33a3koa2 TO /Users/sudarshanv/.ansible/tmp/ansible-tmp-1600984672.921371-61545073908576/AnsiballZ_panos_zone.py
<192.168.1.135> EXEC /bin/sh -c 'chmod u+x /Users/sudarshanv/.ansible/tmp/ansible-tmp-1600984672.921371-61545073908576/ /Users/sudarshanv/.ansible/tmp/ansible-tmp-1600984672.921371-61545073908576/AnsiballZ_panos_zone.py && sleep 0'
<192.168.1.135> EXEC /bin/sh -c '/Users/sudarshanv/Documents/virtualenvs/panos2.0.0/bin/python /Users/sudarshanv/.ansible/tmp/ansible-tmp-1600984672.921371-61545073908576/AnsiballZ_panos_zone.py && sleep 0'
<192.168.1.135> EXEC /bin/sh -c 'rm -f -r /Users/sudarshanv/.ansible/tmp/ansible-tmp-1600984672.921371-61545073908576/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/var/folders/tj/79f9l85j4v14_y5y_h7z5qh40000gn/T/ansible_panos_zone_payload_1fea_wm_/ansible_panos_zone_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/module_utils/panos.py", line 369, in apply_state
    obj.apply()
  File "/Users/sudarshanv/Documents/virtualenvs/panos2.0.0/lib/python3.7/site-packages/panos/base.py", line 585, in apply
    self.xpath(), self.element_str(), retry_on_peer=self.HA_SYNC
  File "/Users/sudarshanv/Documents/virtualenvs/panos2.0.0/lib/python3.7/site-packages/panos/base.py", line 3647, in method
    raise the_exception
failed: [pw-firewall] (item={'Template': 'ansible_test', 'Name': 'ansible1', 'Type': 'layer3', 'Zone Protection Profile': None, 'Log Setting': None, 'User ID Enabled': None}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "invocation": {
        "module_args": {
            "api_key": null,
            "enable_userid": false,
            "exclude_acl": [
                "null"
            ],
            "include_acl": [
                "null"
            ],
            "interface": null,
            "ip_address": null,
            "log_setting": "default",
            "mode": "layer3",
            "password": null,
            "port": 443,
            "provider": {
                "api_key": null,
                "ip_address": "192.168.1.135",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "port": 443,
                "serial_number": null,
                "username": "admin10"
            },
            "state": "present",
            "template": "ansible_test",
            "template_stack": null,
            "username": "admin",
            "vsys": "vsys1",
            "zone": "ansible1",
            "zone_profile": "null"
        }
    },
    "item": {
        "Log Setting": null,
        "Name": "ansible1",
        "Template": "ansible_test",
        "Type": "layer3",
        "User ID Enabled": null,
        "Zone Protection Profile": null
    },
    "msg": "Failed apply:  ansible1 -> network -> zone-protection-profile 'null' is not a valid reference\n ansible1 -> network -> zone-protection-profile is invalid"
}
...ignoring

TASK [debug] **************************************************************************************************************************************
task path: /Users/sudarshanv/Documents/Projects/panos-new/configure_panos.yml:43
ok: [pw-firewall] => (item={'Template': 'ansible_test', 'Name': 'ansible1', 'Type': 'layer3', 'Zone Protection Profile': None, 'Log Setting': None, 'User ID Enabled': None}) => {
    "msg": [
        {
            "provider": {
                "ip_address": "192.168.1.135",
                "password": "4install",
                "username": "admin10"
            }
        },
        {
            "zone": "ansible1"
        },
        {
            "template": "ansible_test"
        },
        {
            "mode": "layer3"
        },
        {
            "zone_profile": "null"
        },
        {
            "log_setting": "default"
        },
        {
            "enable_userid": false
        },
        {
            "include_acl": "null"
        },
        {
            "exclude_acl": "null"
        }
    ]
}

TASK [EXTRACT CURRENT ZONES ON DEVICE] ************************************************************************************************************
task path: /Users/sudarshanv/Documents/Projects/panos-new/configure_panos.yml:58
<192.168.1.135> ESTABLISH LOCAL CONNECTION FOR USER: sudarshanv
<192.168.1.135> EXEC /bin/sh -c 'echo ~sudarshanv && sleep 0'
<192.168.1.135> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/sudarshanv/.ansible/tmp/ansible-tmp-1600984674.979687-84246438734676 `" && echo ansible-tmp-1600984674.979687-84246438734676="` echo /Users/sudarshanv/.ansible/tmp/ansible-tmp-1600984674.979687-84246438734676 `" ) && sleep 0'
Using module file /Users/sudarshanv/.ansible/collections/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_zone_facts.py
<192.168.1.135> PUT /Users/sudarshanv/.ansible/tmp/ansible-local-580937dyuoig_/tmp89j31xdw TO /Users/sudarshanv/.ansible/tmp/ansible-tmp-1600984674.979687-84246438734676/AnsiballZ_panos_zone_facts.py
<192.168.1.135> EXEC /bin/sh -c 'chmod u+x /Users/sudarshanv/.ansible/tmp/ansible-tmp-1600984674.979687-84246438734676/ /Users/sudarshanv/.ansible/tmp/ansible-tmp-1600984674.979687-84246438734676/AnsiballZ_panos_zone_facts.py && sleep 0'
<192.168.1.135> EXEC /bin/sh -c '/Users/sudarshanv/Documents/virtualenvs/panos2.0.0/bin/python /Users/sudarshanv/.ansible/tmp/ansible-tmp-1600984674.979687-84246438734676/AnsiballZ_panos_zone_facts.py && sleep 0'
<192.168.1.135> EXEC /bin/sh -c 'rm -f -r /Users/sudarshanv/.ansible/tmp/ansible-tmp-1600984674.979687-84246438734676/ > /dev/null 2>&1 && sleep 0'
ok: [pw-firewall] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "api_key": null,
            "ip_address": null,
            "name": null,
            "password": null,
            "port": 443,
            "provider": {
                "api_key": null,
                "ip_address": "192.168.1.135",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "port": 443,
                "serial_number": null,
                "username": "admin10"
            },
            "template": "ansible_test",
            "template_stack": null,
            "username": "admin",
            "vsys": "vsys1"
        }
    },
    "zones": [
        {
            "enable_userid": false,
            "exclude_acl": null,
            "include_acl": null,
            "interface": [],
            "log_setting": "default",
            "mode": "layer3",
            "zone": "ansible1",
            "zone_profile": null
        },
        {
            "enable_userid": false,
            "exclude_acl": null,
            "include_acl": null,
            "interface": [],
            "log_setting": "default",
            "mode": "layer3",
            "zone": "ansible2",
            "zone_profile": null
        }
    ]
}
META: ran handlers
META: ran handlers

PLAY RECAP ****************************************************************************************************************************************
pw-firewall                : ok=4    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=1

## Context

Trying to refactor my old code and add a few features.

## Your Environment

- Version used: ansible = 2.9.6, collection == 2.0.0
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): Python 3.7.4
- Operating System and version (desktop or mobile): macos
- Link to your project:

**Comment by mrichardson03** [comment]
Next time, please a relevant playbook snippet along with the issue.

Your playbook isn't providing an empty value to the module, it's providing the string "null", which is then being rejected by PAN-OS:

```
"msg": "Failed apply: ansible1 -> network -> zone-protection-profile 'null' is not a valid reference\n ansible1 -> network -> zone-protection-profile is invalid"
```

You need to be providing a valid [default value](https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#providing-default-values) for that parameter.  Something like:

```
- panos_zone:
    provider: '{{ provider }}'
    zone_profile: '{{ zone_profile | default(omit) }}
```

Which means, if the variable `zone_profile` is not set, don't pass it to the module.

You can also use a string as a default value:

```
- panos_zone:
    provider: '{{ provider }}'
    zone_profile: '{{ zone_profile | default("Default_Zone_Profile") }}'
```

Which will set `zone_profile` to the string "Default_Zone_Profile", which will work if that profile exists on PAN-OS.

**Comment by SudarshanVK** [comment]
Appreciate the quick response, a bit more troubleshooting later in the day and I figured out the issue as to exactly what you pointed out. unfortunately doing | default(omit) does not work in my case because the read from spreadsheet is returning a value of 'null' for empty fields.

When I gather zone facts from Panorama, for any zone that does not have a zone profile configured the value is returned as 'null'. So I do believe there is value in accepting null as an input to the variable and add necessary login in the module to convert it to a format which is accepted by pan-os.

**Comment by mrichardson03** [comment]
I disagree.  The modules are performing in a reasonable way:

- Returning `null` in a dictionary for a possible, but unconfigured value.
- Erroring when a requested profile does not exist.

Your script simply needs to not convert a null value into the string “null”.
