### ISSUE TITLE
Fix args to AnsibleModule.deprecate() for ansible < 2.10

### ISSUE THREAD

**Issue by stealthllama** [PaloAltoNetworks/pan-os-ansible#133]
## Describe the bug

In-code deprecation warnings support a `collection_name` argument starting in Ansible 2.10.  The collection helper is calling `AnsibleModule.deprecate()` when the [pan-os-python](https://pypi.org/project/pan-os-python/) SDK is not installed and needs to revert to using [pandevice](https://pypi.org/project/pandevice/).  If this is done on Ansible versions < 2.10, the `collection_name` argument is not valid.

## Expected behavior

Module execution on Ansible versions < 2.10 should trigger a deprecation warning that instructs users to install [pan-os-python](https://pypi.org/project/pan-os-python/).

## Current behavior

The module fails with an error of:  

File \"/tmp/ansible_panos_security_rule_payload_l8ji8s29/ansible_panos_security_rule_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/module_utils/panos.py\", line 127, in get_pandevice_parent\nTypeError: deprecate() got an unexpected keyword argument 'collection_name'\n"

## Possible solution

Create and pass a conditional argument list based on the value of `AnsibleModule.ansible_version`.

## Steps to reproduce

Run a 2.0.0 collection module on a host without [pan-os-python](https://pypi.org/project/pan-os-python/) and running Ansible version < 2.10.

## Screenshots

N/A

## Your Environment

Ansible 2.9
no [pan-os-python](https://pypi.org/project/pan-os-python/)

**Comment by mrichardson03** [comment]
`collection_name` is supported in Ansible 2.9.10 and above.

https://github.com/ansible/ansible/blob/stable-2.9/changelogs/CHANGELOG-v2.9.rst#id72

**Comment by stealthllama** [comment]
In that case, we should add `requires_ansible: ">=2.9.10"` to the `meta/runtime.yml` file.

**Comment by sry9681** [comment]
I have seem to run into this issue while using Ansible version 2.9.13 and with pan-os-python installed on the venv. Here is the error message.
`{
    "module_stdout": "",
    "module_stderr": "Traceback (most recent call last):\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1637007406.7053158-984-97063982629525/AnsiballZ_panos_facts.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1637007406.7053158-984-97063982629525/AnsiballZ_panos_facts.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1637007406.7053158-984-97063982629525/AnsiballZ_panos_facts.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.paloaltonetworks.panos.plugins.modules.panos_facts', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_paloaltonetworks.panos.panos_facts_payload_598ccph2/ansible_paloaltonetworks.panos.panos_facts_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_facts.py\", line 603, in <module>\n  File \"/tmp/ansible_paloaltonetworks.panos.panos_facts_payload_598ccph2/ansible_paloaltonetworks.panos.panos_facts_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_facts.py\", line 531, in main\n  File \"/tmp/ansible_paloaltonetworks.panos.panos_facts_payload_598ccph2/ansible_paloaltonetworks.panos.panos_facts_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/module_utils/panos.py\", line 133, in get_pandevice_parent\nTypeError: deprecate() got an unexpected keyword argument 'collection_name'\n",
    "exception": "Traceback (most recent call last):\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1637007406.7053158-984-97063982629525/AnsiballZ_panos_facts.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1637007406.7053158-984-97063982629525/AnsiballZ_panos_facts.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1637007406.7053158-984-97063982629525/AnsiballZ_panos_facts.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.paloaltonetworks.panos.plugins.modules.panos_facts', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_paloaltonetworks.panos.panos_facts_payload_598ccph2/ansible_paloaltonetworks.panos.panos_facts_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_facts.py\", line 603, in <module>\n  File \"/tmp/ansible_paloaltonetworks.panos.panos_facts_payload_598ccph2/ansible_paloaltonetworks.panos.panos_facts_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_facts.py\", line 531, in main\n  File \"/tmp/ansible_paloaltonetworks.panos.panos_facts_payload_598ccph2/ansible_paloaltonetworks.panos.panos_facts_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/module_utils/panos.py\", line 133, in get_pandevice_parent\nTypeError: deprecate() got an unexpected keyword argument 'collection_name'\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1,
    "_ansible_no_log": false,
    "changed": false
}`
