### ISSUE TITLE
Error in panos_commit module

### ISSUE THREAD

**Issue by achoudh5** [PaloAltoNetworks/pan-os-ansible#148]
## Describe the bug

I am getting an error while using panos_commit module in ansible

## Expected behavior

It should commit the changes to the device I am giving using variable

## Current behavior

 I am using **panos_commit** in ansible and getting this error:-

`"msg": "Failed commit-all: Commit failed"`

**My task look something like:-**

        - name: commit changes by specified admins to firewall
          panos_commit:
            provider: "{{ panorama_provider }}"
            device_group: '{{ Device }}'

**Runnning using**:- `ansible-playbook -e 'Device=<device_name>' auto.yaml`

## Your Environment

- Python: 3.8
- Ansible: 2.8.5

**Comment by mrichardson03** [comment]
Please read the README.  You can't be using this collection with Ansible 2.8.5, because collection support wasn't added until Ansible 2.9.  Please upgrade to Ansible 2.9.10 (minimum supported version), install the collection, and try again.

**Comment by achoudh5** [comment]
@mrichardson03 I am still getting the same message:-

- Python: 3.8
- Ansible: 2.10.2

`"msg": "Failed commit-all: Commit failed"`

**Comment by mrichardson03** [comment]
What version of the collection are you using?

That message isn’t a failure message with the module, it’s telling you that the config on Panorama has an error and won’t commit.

**Comment by achoudh5** [comment]
> What version of the collection are you using?
> 
> That message isn’t a failure message with the module, it’s telling you that the config on Panorama has an error and won’t commit.

`paloaltonetworks.panos 2.1.0`
