### ISSUE TITLE
Unable to configure Service Routes to permit access to external services and updates.

### ISSUE THREAD

**Issue by Tacmatricx** [PaloAltoNetworks/pan-os-ansible#153]
Unable to configure service routes similar to the command below using the pan-os-ansible modules included in this repository.
set deviceconfig system route service paloalto-networks-services source address 198.51.100.1/24

Working on a playbook to fully build a PaloAlto hardware firewall using Ansible alone. This is the first wall I have hit so far.
I have a workaround in place and will report back with any further core configurations not supported by modules in this repository.

Apologies if this functionality already exists but I'm unable to find any mention of this option.
If this does not already exist, a new module or an expansion of the panos_mgtconfig to support this option would be ideal.

**Comment by mrichardson03** [comment]
The workaround to this would be to use [panos_type_cmd](https://paloaltonetworks.github.io/pan-os-ansible/modules/panos_type_cmd.html) to send the API commands directly.

**Comment by Tacmatricx** [comment]
Thanks, will have to learn the xpath locations.

Does xpath require the api key to be set first, I imagine this would be required.

Will post the play here when I get it working.

**Comment by Tacmatricx** [comment]
Sorted:

admin@PA> show config running

config {
  devices {
    localhost.localdomain {
      deviceconfig {
        system {
          route {
            service {
              paloalto-networks-services {
                source {
                  address 192.168.100.254/24;

NOTE: The IP address above must first be configured on an interface for it to be accepted.

- name: Configure route service
  paloaltonetworks.panos.panos_type_cmd:
    provider: '{{ provider }}'
    xpath: |
      /config/devices/entry[@name='localhost.localdomain']
      /deviceconfig/system/route/service
    element: |
      <entry name="paloalto-networks-services">
        <source>
          <address>192.168.100.254/24</address>
        </source>
      </entry>

admin@PA> show config running xpath devices/entry[@name='localhost.localdomain']/deviceconfig/system/route/service

**Comment by Tacmatricx** [comment]
Also, the API key is not needed for this. I was able to run that play using only SSH credentials.
