### ISSUE TITLE
Match Security Rule Fails on Truncated Rule Names

### ISSUE THREAD

**Issue by jvanderaa** [PaloAltoNetworks/pan-os-ansible#180]
## Describe the bug

With long names of the rule, the API from Palo truncates the name of the rule

## Expected behavior

I'd expect it to find the rule

## Current behavior

Currently fails the execution instead of returning the action of the rule

## Steps to reproduce

1. Have a rule with a long name
2. Have a test command issued against that would match the long rule name
3. Get a failure message.

## Context

Trying to find where to put a new rule to allow new permits.

## Your Environment

- Collection: 2.4
- Python: 3.7
- Ansible: 2.9.15

**Comment by mrichardson03** [comment]
Out of curiosity, what happens if you use `panos_security_rule_facts`?

**Comment by jvanderaa** [comment]
Those are coming in with the right full length names.

**Comment by mrichardson03** [comment]
Please use `panos_security_rule_facts`.  It is a more modern implementation of the same functionality.
