### ISSUE TITLE
panos_address_group does not allow additions.  Group is rewritten in a loop.  Old group allowed add keyword

### ISSUE THREAD

**Issue by dpflick** [PaloAltoNetworks/pan-os-ansible#198]
## Describe the bug

When looping through items in a list, I can no longer add items with each loop iteration like I could with panos_sag.  This makes it very difficult to build a list of objects and then add them to a group.

## Expected behavior

A command like panos_sag "operation" with add/remove/replace would allow users to loop through list items and add them to a group.

## Current behavior

  panos_address_group:
    provider: '{{ provider }}'
    name: 'RapidSOS-Client'
    static_value: '{{ item.addr_object_name }}'
    description: 'Allowed Internet DNS'
  with_items:
    - '{{ rapidsos-client }}'

this will OVERWRITE items in the rapidsos-client list so only the last item is in the group.

## Possible solution

add an operation key with values add/remove/replace so that groups could be built/pruned/replaced with loops.

## Steps to reproduce

This snippet of code:
variables:
rapidsos-client:
  -client1
  -client2
  -client3

  panos_address_group:
    provider: '{{ provider }}'
    name: 'RapidSOS-Client'
    static_value: '{{ item.addr_object_name }}'
    description: 'Allowed Internet DNS'
  with_items:
    - '{{ rapidsos-client }}'

builds a address group with 1 member (client3)

This deprecated code:
rapidsos-client:
  -client1
  -client2
  -client3
  panos_sag:
    ip_address: '{{ fw_ip_address }}'
    username: '{{ fw_username }}'
    password: '{{ fw_password }}'
    sag_name: 'RapidSOS-Client'
    sag_match_filter: [ '{{ item.object_name }}' ]
    description:  'Allowed Internet DNS'
    operation: add
    commit: false
  with_items:
    - '{{ rapidsos-client }}'
 
builds a address group with all three members (client1, client2, client3)  

## Context

We are automating the building a number of objects that need identical access and then placing those objects into an address-group for inclusion in policies.

## Your Environment

- Collection: paloaltonetworks.panos
- Python: 3.6
- Ansible: 2.10
- PAN-OS Python Library & version latest

**Comment by mrichardson03** [comment]
`static_value` can take a list as input, so this shouldn't be required.

**Comment by dpflick** [comment]
So I can’t iterate through a loop using static value and have it be additive though, correct?  Based on what you are saying, I am thinking that each time I loop over, it will REPLACE the existing value.

I could probably loop through the list and generate a single list  earlier in the code and then run panos_address_group on the generated variable I would think.

Anyone else run into this and have a better solution?

**Comment by mrichardson03** [comment]
Appending to the group is a bad solution for a few reasons: it would break the idempotent operation of the module, and it would result in far more API calls than necessary (two for each element in your loop, rather than two total) making the module slow.

You should calculate the list, then call the module once once it's been done.

**Comment by dpflick** [comment]
Thanks!  That helps a lot.  I am not coming from a programming background but that makes plenty of sense.
