### ISSUE TITLE
Connection to Palo firewall resulting in "Tunnel connection failed: 503 Service Unavailable"

### ISSUE THREAD

**Issue by achhabr1** [PaloAltoNetworks/pan-os-ansible#210]
## Describe the bug

Hi, I am trying to back up pan os configuration file using export module, I am seeing below error and not able to figure out what. might be causing it. Looks like some setting needs to be enabled on the firewall to make this happen. 

(python3env) [ac043s@SDNAUTOS02 panos]$ ansible-playbook -i hosts panos_backup.yml -vvvvv
ansible-playbook 2.10.8
  config file = /home/ac043s/software/ansible_development/panos/ansible.cfg
  configured module search path = ['/home/ac043s/.ansible']
  ansible python module location = /home/ac043s/python3-virtual-environments/python3env/lib64/python3.6/site-packages/ansible
  executable location = /home/ac043s/python3-virtual-environments/python3env/bin/ansible-playbook
  python version = 3.6.12 (default, Sep 15 2020, 12:49:31) [GCC 4.4.7 20120313 (Red Hat 4.4.7-23)]
Using /home/ac043s/software/ansible_development/panos/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /home/ac043s/software/ansible_development/panos/hosts as it did not pass its verify_file() method
script declined parsing /home/ac043s/software/ansible_development/panos/hosts as it did not pass its verify_file() method
auto declined parsing /home/ac043s/software/ansible_development/panos/hosts as it did not pass its verify_file() method
Parsed /home/ac043s/software/ansible_development/panos/hosts inventory source with ini plugin
Loading collection paloaltonetworks.panos from /home/ac043s/python3-virtual-environments/python3env/lib64/python3.6/site-packages/ansible_collections/paloaltonetworks/panos
Loading callback plugin default of type stdout, v2.0 from /home/ac043s/python3-virtual-environments/python3env/lib64/python3.6/site-packages/ansible/plugins/callback/default.py
Attempting to use 'default' callback.
Skipping callback 'default', as we already have a stdout callback.
Attempting to use 'junit' callback.
Attempting to use 'minimal' callback.
Skipping callback 'minimal', as we already have a stdout callback.
Attempting to use 'oneline' callback.
Skipping callback 'oneline', as we already have a stdout callback.
Attempting to use 'tree' callback.

PLAYBOOK: panos_backup.yml ************************************************************************************************************************************************************************************
Positional arguments: panos_backup.yml
verbosity: 5
connection: smart
timeout: 10
become_method: sudo
tags: ('all',)
inventory: ('/home/ac043s/software/ansible_development/panos/hosts',)
forks: 20
1 plays in panos_backup.yml

PLAY [Bcakup Palo Alto device configuration.] *****************************************************************************************************************************************************************
META: ran handlers

TASK [Export configuration] ***********************************************************************************************************************************************************************************
task path: /home/ac043s/software/ansible_development/panos/panos_backup.yml:20
<ga-u350-14-vfw> ESTABLISH LOCAL CONNECTION FOR USER: ac043s
<ga-u350-14-vfw> EXEC /bin/sh -c 'echo ~ac043s && sleep 0'
<ga-u350-14-vfw> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ac043s/.ansible/tmp `"&& mkdir "` echo /home/ac043s/.ansible/tmp/ansible-tmp-1618846709.5008986-29399-131746391824607 `" && echo ansible-tmp-1618846709.5008986-29399-131746391824607="` echo /home/ac043s/.ansible/tmp/ansible-tmp-1618846709.5008986-29399-131746391824607 `" ) && sleep 0'
Including module_utils file ansible/__init__.py
Including module_utils file ansible/module_utils/__init__.py
Including module_utils file ansible/module_utils/basic.py
Including module_utils file ansible/module_utils/_text.py
Including module_utils file ansible/module_utils/common/_collections_compat.py
Including module_utils file ansible/module_utils/common/__init__.py
Including module_utils file ansible/module_utils/common/_json_compat.py
Including module_utils file ansible/module_utils/common/_utils.py
Including module_utils file ansible/module_utils/common/file.py
Including module_utils file ansible/module_utils/common/parameters.py
Including module_utils file ansible/module_utils/common/collections.py
Including module_utils file ansible/module_utils/common/process.py
Including module_utils file ansible/module_utils/common/sys_info.py
Including module_utils file ansible/module_utils/common/text/converters.py
Including module_utils file ansible/module_utils/common/text/__init__.py
Including module_utils file ansible/module_utils/common/text/formatters.py
Including module_utils file ansible/module_utils/common/validation.py
Including module_utils file ansible/module_utils/common/warnings.py
Including module_utils file ansible/module_utils/compat/selectors.py
Including module_utils file ansible/module_utils/compat/__init__.py
Including module_utils file ansible/module_utils/compat/_selectors2.py
Including module_utils file ansible/module_utils/distro/__init__.py
Including module_utils file ansible/module_utils/distro/_distro.py
Including module_utils file ansible/module_utils/parsing/convert_bool.py
Including module_utils file ansible/module_utils/parsing/__init__.py
Including module_utils file ansible/module_utils/pycompat24.py
Including module_utils file ansible/module_utils/six/__init__.py
Including module_utils file ansible_collections/paloaltonetworks/panos/plugins/module_utils/panos.py
Including module_utils file ansible_collections/__init__.py
Including module_utils file ansible_collections/paloaltonetworks/__init__.py
Including module_utils file ansible_collections/paloaltonetworks/panos/__init__.py
Including module_utils file ansible_collections/paloaltonetworks/panos/plugins/__init__.py
Including module_utils file ansible_collections/paloaltonetworks/panos/plugins/module_utils/__init__.py
Using module file /home/ac043s/python3-virtual-environments/python3env/lib64/python3.6/site-packages/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_export.py
<ga-u350-14-vfw> PUT /home/ac043s/.ansible/tmp/ansible-local-29392u2t2hktb/tmp1bhqp8v4 TO /home/ac043s/.ansible/tmp/ansible-tmp-1618846709.5008986-29399-131746391824607/AnsiballZ_panos_export.py
<ga-u350-14-vfw> EXEC /bin/sh -c 'chmod u+x /home/ac043s/.ansible/tmp/ansible-tmp-1618846709.5008986-29399-131746391824607/ /home/ac043s/.ansible/tmp/ansible-tmp-1618846709.5008986-29399-131746391824607/AnsiballZ_panos_export.py && sleep 0'
<ga-u350-14-vfw> EXEC /bin/sh -c '/home/ac043s/python3-virtual-environments/python3env/bin/python /home/ac043s/.ansible/tmp/ansible-tmp-1618846709.5008986-29399-131746391824607/AnsiballZ_panos_export.py && sleep 0'
<ga-u350-14-vfw> EXEC /bin/sh -c 'rm -f -r /home/ac043s/.ansible/tmp/ansible-tmp-1618846709.5008986-29399-131746391824607/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_panos_export_payload_57rxkbzb/ansible_panos_export_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/module_utils/panos.py", line 167, in get_pandevice_parent
    self.device = PanDevice.create_from_device(*pan_device_auth)
  File "/home/ac043s/python3-virtual-environments/python3env/lib64/python3.6/site-packages/panos/base.py", line 3496, in create_from_device
    system_info = device.refresh_system_info()
  File "/home/ac043s/python3-virtual-environments/python3env/lib64/python3.6/site-packages/panos/base.py", line 3938, in refresh_system_info
    system_info = self.show_system_info()
  File "/home/ac043s/python3-virtual-environments/python3env/lib64/python3.6/site-packages/panos/base.py", line 3895, in show_system_info
    root = self.xapi.op(cmd="show system info", cmd_xml=True)
  File "/home/ac043s/python3-virtual-environments/python3env/lib64/python3.6/site-packages/panos/base.py", line 3748, in xapi
    self._xapi_private = self.generate_xapi()
  File "/home/ac043s/python3-virtual-environments/python3env/lib64/python3.6/site-packages/panos/base.py", line 3801, in generate_xapi
    "api_key": self.api_key,
  File "/home/ac043s/python3-virtual-environments/python3env/lib64/python3.6/site-packages/panos/base.py", line 3742, in api_key
    self._api_key = self._retrieve_api_key()
  File "/home/ac043s/python3-virtual-environments/python3env/lib64/python3.6/site-packages/panos/base.py", line 3888, in _retrieve_api_key
    xapi.keygen(retry_on_peer=False)
  File "/home/ac043s/python3-virtual-environments/python3env/lib64/python3.6/site-packages/panos/base.py", line 3645, in method
    raise the_exception
fatal: [ga-u350-14-vfw]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "api_key": null,
            "application_pcap_name": null,
            "category": "configuration",
            "certificate_format": null,
            "certificate_include_keys": false,
            "certificate_name": null,
            "certificate_passphrase": null,
            "dlp_password": null,
            "dlp_pcap_name": null,
            "filename": "running-config.xml",
            "filter_pcap_name": null,
            "ip_address": null,
            "password": null,
            "port": 443,
            "provider": {
                "api_key": null,
                "ip_address": "ga-u350-14-vfw",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "port": 22,
                "serial_number": null,
                "username": "admin"
            },
            "threat_pcap_id": null,
            "threat_pcap_search_time": null,
            "threat_pcap_serial": null,
            "timeout": 600,
            "username": "admin"
        }
    },
    "msg": "Failed connection: URLError: reason: Tunnel connection failed: 503 Service Unavailable"
}

PLAY RECAP ****************************************************************************************************************************************************************************************************
ga-u350-14-vfw             : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

(python3env) [ac043s@SDNAUTOS02 panos]$ 

Playbook --

---
- name: "Bcakup Palo Alto device configuration."
  hosts: paloalto
  connection: local
  gather_facts: no

  vars:
    device:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      port: 22
    
    ansible_python_interpreter: "{{ lookup('env', 'HOME') }}/python3-virtual-environments/python3env/bin/python"
  
  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Export configuration
      panos_export:
        provider: '{{ device }}'
        category: 'configuration'
        filename: 'running-config.xml'

**Comment by mrichardson03** [comment]
This Ansible collection uses the XML-API for communication with the device, not SSH.  Please reference the documentation and examples for proper usage.
