### ISSUE TITLE
Intermittent 403 - Failed Connection Errors in Ansible Playbook against Panorama Device

### ISSUE THREAD

**Issue by sikulkar** [PaloAltoNetworks/pan-os-ansible#226]
## Describe the bug

I have an ansible playbook running againsts Panorama device that creates address,service objects -> security policy -> Commit and push to different device groups. 
Randomly one of the task fails during executing with the error - Failed Connection: URL Error: code: 403 reason: Forbidden. 
This is not specific to any particular module and have seen it happening in panos_address_object, panos_commit_push etc

## Expected behavior

The playbook should not fail on the intermittent 403 error message. The TACACS server configuration, role has been verified. 

## Current behavior

The Playbook fails on a random task - either panos_address_object,panos_commit_push  or even read operations. Attaching the screenshot for reference

## Steps to reproduce

This issue doesn't happen always and hard to repro. But in general steps to re-produce is just to run the playbook.

## Screenshots

<img width="686" alt="403_error_ansible_scrubed" src="https://user-images.githubusercontent.com/49550250/119036154-49726000-b965-11eb-9eeb-3a5822a264b6.png">

## Context

This playbook is part of our end to end automation which processes customer tickets and implements the security policies globally. With this issue occuring, it basically breaks/fails our automation and engineer has to manually login into the device and implement the rest of the changes. 

Since the error happens at any task, we have uncommitted changes on Production panorama and manual attention is needed. The automation workflow is triggered manually at this point, but it prevents it from automating this workflow around the clock since our customers are all across the globe.

## Your Environment

- Collection:
- Python: 3.8
- Ansible: 2.9.10 , Tower 3.4.3
- PAN-OS Python Library & version - PaloAltoNetworks/pan-os-ansible v2.0.0

**Comment by Spacebjorn** [comment]
In my own experience, making too many requests towards panorama in a loop causes this. I have fixed this by setting the [throttle property](https://docs.ansible.com/ansible/latest/user_guide/playbooks_strategies.html#restricting-execution-with-throttle) to 1 so Ansible only runs each task in a sequential order. i.e. if you have 3 hosts it will first loop all the way through the task on host 1, then host 2 and then host 3.

Additionally in my loops I have set the [loop_control pause property ](https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html#pausing-within-a-loop)to 1 so it waits 1 second between each requests.

**Comment by sikulkar** [comment]
@Spacebjorn - Thank you for the suggestion. This was helpful to fix the issue :)
