### ISSUE TITLE
panos_api_key.py seems odd

### ISSUE THREAD

**Issue by natbrood** [PaloAltoNetworks/pan-os-ansible#239]
## Documentation link
[link](https://github.com/PaloAltoNetworks/pan-os-ansible/blob/3c3619cfad517e4e6d9afe86c84fb8f437929eec/plugins/modules/panos_api_key.py)

## Describe the problem
Correct me if I'm wrong, but this says you need an api key to get an api key. Chicken and egg.
How do I enter this loop (besides a manual http post to the host)

## Suggested fix
Update the Synopsis (since it implies the ability to get the api key with just a username:password) or give some examples of how you can request the initial api key

**Comment by shinmog** [comment]
Both `DOCUMENTATION.short_description` and `DOCUMENTATION.description` say that you can get an API key for a given username/password combo.  That being said, the standard documentation fragment will have an API key arg, but it's optional.  Just give either `username`/`password` (these are classic style and will be removed in a future version of the collection) or `provider.username`/`provider.password`.

**Comment by shinmog** [comment]
Seems this is resolved, closing
