### ISSUE TITLE
PAN-OS software upgrade timeout

### ISSUE THREAD

**Issue by bizmark07** [PaloAltoNetworks/pan-os-ansible#263]
## Describe the bug

paloaltonetworks.panos.panos_software times out. 

PAN-OS target version is downloaded and installed but ansible playbook times out.

This is using the [upgrade-single.yml](https://github.com/PaloAltoNetworks/ansible-playbooks/blob/master/upgrade_single.yml) playbook from the repo. 

## Expected behavior

I'd expect the install task to terminate when the firewall reboots (loses connectivity) or attempt to establish a new session periodically until the firewall reboots and it's able to reconnect. 

## Current behavior

- playbook connects to firewall
- downloads version
- installs image
- reboots firewall
- install task times out

playbook debug -vvvv for specific task that fails

`TASK [Install target PAN-OS version] *****************************************************************************************************************************************************************************************************************
task path: /home/user123/Documents/Scripts/ans/cs-upgrade.yml:31
<firewall> ESTABLISH LOCAL CONNECTION FOR USER: user123
<firewall> EXEC /bin/sh -c 'echo ~user123 && sleep 0'
<firewall> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/user123/.ansible/tmp `"&& mkdir "` echo /home/user123/.ansible/tmp/ansible-tmp-1631915005.186448-76430-39963681705318 `" && echo ansible-tmp-1631915005.186448-76430-39963681705318="` echo /home/user123/.ansible/tmp/ansible-tmp-1631915005.186448-76430-39963681705318 `" ) && sleep 0'
Using module file /home/user123/.ansible/collections/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_software.py
<firewall> PUT /home/user123/.ansible/tmp/ansible-local-76312srb22j6x/tmp9uzaky5a TO /home/user123/.ansible/tmp/ansible-tmp-1631915005.186448-76430-39963681705318/AnsiballZ_panos_software.py
<firewall> EXEC /bin/sh -c 'chmod u+x /home/user123/.ansible/tmp/ansible-tmp-1631915005.186448-76430-39963681705318/ /home/user123/.ansible/tmp/ansible-tmp-1631915005.186448-76430-39963681705318/AnsiballZ_panos_software.py && sleep 0'
<firewall> EXEC /bin/sh -c '/usr/bin/python3 /home/user123/.ansible/tmp/ansible-tmp-1631915005.186448-76430-39963681705318/AnsiballZ_panos_software.py && sleep 0'`

Full traceback

`The full traceback is:
Traceback (most recent call last):
  File "/home/user123/.ansible/tmp/ansible-tmp-1631928429.3373044-89147-181462103359991/AnsiballZ_panos_software.py", line 100, in <module>
    _ansiballz_main()
  File "/home/user123/.ansible/tmp/ansible-tmp-1631928429.3373044-89147-181462103359991/AnsiballZ_panos_software.py", line 92, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/user123/.ansible/tmp/ansible-tmp-1631928429.3373044-89147-181462103359991/AnsiballZ_panos_software.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.paloaltonetworks.panos.plugins.modules.panos_software', init_globals=dict(_module_fqn='ansible_collections.paloaltonetworks.panos.plugins.modules.panos_software', _modlib_path=modlib_path),
  File "/usr/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_paloaltonetworks.panos.panos_software_payload_jeu070g6/ansible_paloaltonetworks.panos.panos_software_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_software.py", line 222, in <module>
  File "/tmp/ansible_paloaltonetworks.panos.panos_software_payload_jeu070g6/ansible_paloaltonetworks.panos.panos_software_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_software.py", line 212, in main
  File "/home/user123/Documents/Scripts/ans/upgradeTest/venv/lib/python3.8/site-packages/panos/base.py", line 4287, in restart
    self.xapi.op("request restart system", cmd_xml=True)
  File "/home/user123/Documents/Scripts/ans/upgradeTest/venv/lib/python3.8/site-packages/panos/base.py", line 3661, in method
    super_method(self, *args, **kwargs)
  File "/home/user123/Documents/Scripts/ans/upgradeTest/venv/lib/python3.8/site-packages/pan/xapi.py", line 951, in op
    self.__type_op(cmd, vsys, extra_qs)
  File "/home/user123/Documents/Scripts/ans/upgradeTest/venv/lib/python3.8/site-packages/pan/xapi.py", line 969, in __type_op
    response = self.__api_request(query)
  File "/home/user123/Documents/Scripts/ans/upgradeTest/venv/lib/python3.8/site-packages/pan/xapi.py", line 545, in __api_request
    response = urlopen(**kwargs)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.8/urllib/request.py", line 1358, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out`

## Possible solution

Seems like a requests retry is failing. The readthedocs page states "After performing the software install, returns the version installed on the device." Seems to imply that this module will reconnect after the firewall reboots in the same task. 

## Steps to reproduce

1. Run upgrade-single.yml playbook against panos 10.0.5. set version as 10.0.6 (experienced the same going from 9.0.0 to 9.0.14)

## Context

Attempting to use this playbook to ease real-world bulk upgrade scenario. 

## Your Environment

- Collection: 2.8.0 (also test 2.7.0)
- Python:Python 3.8.10 (virtualenv)
- Ansible: ansible core 2.11.5
- PAN-OS Python Library & version (e.g. pandevice 0.14.0, pan-os-python 1.0.2):
pan-os-python      1.4.0
pan-python         0.16.0
pandevice          0.14.0

**Comment by jamesholland-uk** [comment]
The [linked playbook](https://github.com/PaloAltoNetworks/ansible-playbooks/blob/master/upgrade_single.yml) is working ok for me, is it something local in your environment?

collection 2.8.0
python 3.9.5 
ansible core 2.11.5
pan-os-python 1.4.0
pan-python 0.16.0
pandevice 0.14.0

```
TASK [Install target PAN-OS version] *********************************************************************************************************************************************************************************************************************************************
task path: /Users/jholland/code/github/ansible-playbooks/upgrade_single.yml:59
<firewall> ESTABLISH LOCAL CONNECTION FOR USER: jholland
<firewall> EXEC /bin/sh -c 'echo ~jholland && sleep 0'
<firewall> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/jholland/.ansible/tmp `"&& mkdir "` echo /Users/jholland/.ansible/tmp/ansible-tmp-1632153745.83246-75993-33406650260012 `" && echo ansible-tmp-1632153745.83246-75993-33406650260012="` echo /Users/jholland/.ansible/tmp/ansible-tmp-1632153745.83246-75993-33406650260012 `" ) && sleep 0'
Using module file /Users/jholland/.ansible/collections/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_software.py
<firewall> PUT /Users/jholland/.ansible/tmp/ansible-local-759339udnriyi/tmpmo5pdqej TO /Users/jholland/.ansible/tmp/ansible-tmp-1632153745.83246-75993-33406650260012/AnsiballZ_panos_software.py
<firewall> EXEC /bin/sh -c 'chmod u+x /Users/jholland/.ansible/tmp/ansible-tmp-1632153745.83246-75993-33406650260012/ /Users/jholland/.ansible/tmp/ansible-tmp-1632153745.83246-75993-33406650260012/AnsiballZ_panos_software.py && sleep 0'
<firewall> EXEC /bin/sh -c '/Users/jholland/code/github/ansible-playbooks/.venv/bin/python /Users/jholland/.ansible/tmp/ansible-tmp-1632153745.83246-75993-33406650260012/AnsiballZ_panos_software.py && sleep 0'
<firewall> EXEC /bin/sh -c 'rm -f -r /Users/jholland/.ansible/tmp/ansible-tmp-1632153745.83246-75993-33406650260012/ > /dev/null 2>&1 && sleep 0'
changed: [firewall] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "api_key": null,
            "download": true,
            "install": true,
            "ip_address": null,
            "password": null,
            "port": 443,
            "provider": {
                "api_key": null,
                "ip_address": "192.168.150.241",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "port": 443,
                "serial_number": null,
                "username": "admin"
            },
            "restart": true,
            "sync_to_peer": false,
            "timeout": 1200,
            "username": "admin",
            "version": "10.1.1"
        }
    },
    "version": "10.1.1"
}

TASK [Pause for restart] *********************************************************************************************************************************************************************************************************************************************************
task path: /Users/jholland/code/github/ansible-playbooks/upgrade_single.yml:65
Pausing for 30 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
ok: [firewall] => {
    "changed": false,
    "delta": 30,
    "echo": true,
    "rc": 0,
    "start": "2021-09-20 17:04:48.403968",
    "stderr": "",
    "stdout": "Paused for 30.0 seconds",
    "stop": "2021-09-20 17:05:18.406210",
    "user_input": ""
}

TASK [Check to see if device is ready] *******************************************************************************************************************************************************************************************************************************************
```

**Comment by bizmark07** [comment]
I deployed another firewall in my local network and the playbook has been running consistently without any changes. My original environment is still failing. I'm not what impact this might have but it seems the only difference is latency. All I'm changing is the ip_address variable in the host vars. 

Working lab environment: approx 6ms
Failing lab environment: approx 67ms

I'm going to attempt to get an ansible instances closer to the failing environment to further test

**Comment by Leanessc1** [comment]
After some testing I opened enhancement - #285.  

Looks like we get the same error if the Mgmt interface traffic needs to traverse the dataplane of the FW being restarted.  The SSH session to the Mgmt interface is never able to reform due to the dataplane dropping the traffic from ansible post restart.  I believe this is due to the traffic being seen on the dataplane as not having an open session and not being initiated with a 3 way handshake.  

@bizmark07 - Is this the same thing you were experiencing?

**Comment by 3NogfqYs** [comment]
To add weight to what @Leanessc1 mentions. I see this issue when upgrading firewalls that provide the IPSec connectivity back to the sire where ansible is run from. The connection drop before ansible gets a response to the restart request so the task just hangs.
