### ISSUE TITLE
panos_l3_subinterface: no commit parameter

### ISSUE THREAD

**Issue by jakunow** [PaloAltoNetworks/pan-os-ansible#28]
### Is your feature request related to a problem?

Most of modules have **commit** parameter but this one doesn't

### Describe the solution you'd like

Add commit parameter to this module to have it consistent with rest

### Describe alternatives you've considered

N/A

### Additional context

Most modules have this parameter, would be good to keep this one consistent with others.

**Comment by mrichardson03** [comment]
We're planning on phasing out per-module commits in favor of using `panos_commit` everywhere.  See [this issue](https://github.com/PaloAltoNetworks/pan-os-ansible/issues/35) for more information.

**Comment by jakunow** [comment]
If per-module commit behavior will be removed from all modules in #35, then closing this one. Thanks.
