### ISSUE TITLE
panos_ha fails on vm-series in Azure

### ISSUE THREAD

**Issue by jonolenome** [PaloAltoNetworks/pan-os-ansible#31]
Running ansible playbook to configure active-passive ha cluster in Azure fails.

## Describe the bug
I am running a playbook to configure interfaces, routing etc. of a pair of vm-series 300 in Azure. I am trying to also automate the HA config and have added the following to the playbook:

    - name: Configure Active/Standby HA
      panos_ha:
        provider: "{{provider}}"
        state: present
        ha_peer_ip: "10.75.0.53"
        ha1_ip_address: "10.75.0.52"
        ha1_netmask: "255.255.255.240"
        ha1_port: "management"
        ha2_port: "ethernet1/3"
        ha_mode: "active-passive"
        commit: "false"

## Expected behavior

HA configuration succeeds.

## Current behavior
TASK [Configure Active/Standby HA] ******************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed apply:  high-availability -> interface -> ha1-backup unexpected here\n high-availability -> interface is invalid"}

## Steps to reproduce

1.
2.
3.
4.

## Your Environment
Using the paloaltonetworks.panos:1.1.0 collection with ansible 2.9.4 on Ubuntu 16.04.06 (WSL).

**Comment by jamesholland-uk** [comment]
With the latest version of the collection, this error no longer occurs. Believe this was fixed with https://github.com/PaloAltoNetworks/pan-os-python/pull/351
