### ISSUE TITLE
panos_ha fails,  list index out of range

### ISSUE THREAD

**Issue by CrimsonBinome24** [PaloAltoNetworks/pan-os-ansible#32]
**Describe the bug**
When playbook attempts to run the panos_ha section it fails due to "list index out of range"

**Expected behavior**
It should be able to  complete as expected

**Current behavior**
when executing play book other panos modules execute correctly, panos_ha module fails.

**Possible solution**
Unknown

**Steps to reproduce**
Execute Playbook

**Relevant Playbook Configuration**:
    - name: set ports to HA mode
      panos_interface:
        provider: '{{ provider }}'
        if_name: "{{ item }}"
        mode: "ha"
        enable_dhcp: false
        commit: false
      with_items:
        - "ethernet1/1"
        - "ethernet1/2"

    - name: Configure Active/Standby HA
      panos_ha:
        provider: "{{ provider }}"
        state: present
        ha_peer_ip: "10.1.1.6"
        ha_peer_ip_backup: "10.1.2.6"
        ha1_ip_address: "10.1.1.5"
        ha1_netmask: "255.255.255.252"
        ha1_port: "ha1-a"
        ha1b_ip_address: "10.1.1.5"
        ha1b_netmask: "255.255.255.252"
        ha1b_port: "ha1-b"
        ha2_ip_address: "10.1.3.5"
        ha2_netmask: "255.255.255.252"
        ha2_port: "ethernet1/1"
        ha2b_ip_address: "10.1.4.5"
        ha2b_netmask: "255.255.255.252"
        ha2b_port: "ethernet1/2"

**Error Message:**
TASK [set ports to HA mode] *****************************************************************************************************************************************************************************************************************
ok: [**-Redacted-**] => (item=ethernet1/1)
ok: [**-Redacted-**] => (item=ethernet1/2)

TASK [Configure Active/Standby HA] **********************************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: IndexError: list index out of range
fatal: [M-PA-CLINSYS]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1593696616.73-40067-259423980504753/AnsiballZ_panos_ha.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1593696616.73-40067-259423980504753/AnsiballZ_panos_ha.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1593696616.73-40067-259423980504753/AnsiballZ_panos_ha.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.paloaltonetworks.panos.plugins.modules.panos_ha', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python2.7/runpy.py\", line 188, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_panos_ha_payload_g89nNP/ansible_panos_ha_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_ha.py\", line 456, in <module>\n  File \"/tmp/ansible_panos_ha_payload_g89nNP/ansible_panos_ha_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_ha.py\", line 443, in main\nIndexError: list index out of range\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

**Your Environment:**
ansible 2.9.10
Device: PA-3260
Pan OS 9.0.4

**Comment by kevinhuy** [comment]
this issue seem happen only at first initialization of ha.

**Comment by jtlutgen** [comment]
i am seeing the same error.  Did this ever get resolved? 

`An exception occurred during task execution. To see the full traceback, use -vvv. The error was: IndexError: list index out of range
fatal: [pod00-pan1]: FAILED! => changed=false 
  module_stderr: |-
    Traceback (most recent call last):
      File "/home/user/.ansible/tmp/ansible-tmp-1621443328.3887355-276360-19259164670020/AnsiballZ_panos_ha.py", line 102, in <module>
        _ansiballz_main()
      File "/home/user/.ansible/tmp/ansible-tmp-1621443328.3887355-276360-19259164670020/AnsiballZ_panos_ha.py", line 94, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/home/user/.ansible/tmp/ansible-tmp-1621443328.3887355-276360-19259164670020/AnsiballZ_panos_ha.py", line 40, in invoke_module
        runpy.run_module(mod_name='ansible_collections.paloaltonetworks.panos.plugins.modules.panos_ha', init_globals=None, run_name='__main__', alter_sys=True)
      File "/usr/lib/python3.8/runpy.py", line 207, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_panos_ha_payload_aimldfl6/ansible_panos_ha_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_ha.py", line 452, in <module>
      File "/tmp/ansible_panos_ha_payload_aimldfl6/ansible_panos_ha_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_ha.py", line 439, in main
    IndexError: list index out of range
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
`

ansible 2.10.9
 python version = 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]
Collection             Version
---------------------- -------
community.general      3.0.1  
paloaltonetworks.panos 2.6.0

**Comment by ntwrkguru** [comment]
This seems to be caused since `listing` returns an empty list prior to initialization of HA. If HA is configured using the UI, the list contains the `HighAvailability` object, as expected. Perhaps a conditional to initialize HA if `len(listing) < 1`, but I'm not sure how to initialize HA via the API to test. Maybe this helps someone with more time than I have. 😄

**Comment by CrimsonBinome24** [comment]
I apologize for the long delay on this update. I have been able to bypass this issue with the following code:

` -name: set ports to HA mode
      panos_interface:
        provider: '{{ provider }}'
        if_name: "{{ item }}"
        mode: "ha"
        enable_dhcp: false
        commit: false
      with_items:
        - "ethernet1/1"
        - "ethernet1/2"

    - name: Configure Port HA1
      panos_type_cmd:
        provider: "{{ provider }}"
        xpath: "/config/devices/entry[@name='localhost.localdomain']/deviceconfig/high-availability/interface"
        element: "<ha1><ip-address>**REDACTED**</ip-address><netmask>255.255.255.252</netmask><port>ha1-a</port></ha1>"

    - name: Configure Port HA1-Backup
      panos_type_cmd:
        provider: "{{ provider }}"
        xpath: "/config/devices/entry[@name='localhost.localdomain']/deviceconfig/high-availability/interface"
        element: "<ha1-backup><ip-address>**REDACTED**</ip-address><netmask>255.255.255.252</netmask><port>ha1-b</port></ha1-backup>"

    - name: Configure Port HA2
      panos_type_cmd:
        provider: "{{ provider }}"
        xpath: "/config/devices/entry[@name='localhost.localdomain']/deviceconfig/high-availability/interface"
        element: "<ha2><ip-address>**REDACTED**</ip-address><netmask>255.255.255.252</netmask><port>ethernet1/1</port></ha2>"

    - name: Configure HA2-Backup
      panos_type_cmd:
        provider: "{{ provider }}"
        xpath: "/config/devices/entry[@name='localhost.localdomain']/deviceconfig/high-availability/interface"
        element: "<ha2-backup><ip-address>**REDACTED**</ip-address><netmask>255.255.255.252</netmask><port>ethernet1/2</port></ha2-backup>"

    - name: Configure HA Group Settings
      panos_type_cmd:
        provider: "{{ provider }}"
        xpath: "/config/devices/entry[@name='localhost.localdomain']/deviceconfig/high-availability/group"
        element: "<state-synchronization><enabled>yes</enabled></state-synchronization><group-id>2</group-id><peer-ip>10.1.1.6</peer-ip><peer-ip-backup>**REDACTED**</peer-ip-backup>"

    - name: Enable HA
      panos_type_cmd:
        provider: "{{ provider }}"
        xpath: "/config/devices/entry[@name='localhost.localdomain']/deviceconfig/high-availability"
        element: "<enabled>yes</enabled>"   
`

**Comment by ntwrkguru** [comment]
@CrimsonBinome24 thanks for the update and workaround. Coincidentally, check out the `panos_config_element` module that was recently released to perform those element insertions.

**Comment by CrimsonBinome24** [comment]
> @CrimsonBinome24 thanks for the update and workaround. Coincidentally, check out the `panos_config_element` module that was recently released to perform those element insertions.

Will do, Thanks! its been a while since I wrote these scripts so I will most likely need to do a review at some point.
