### ISSUE TITLE
Request help on "Missing required library \"pan-os-python\"." error

### ISSUE THREAD

**Issue by shermannws** [PaloAltoNetworks/pan-os-ansible#324]
## Describe the bug
When executing in AAP2.2 controller, using the `panos_object` module throws error that `"Missing required library \"pan-os-python\"."`.

## Expected behavior
Expect template to run without error. Using the same playbook and same collection versions in Tower passed without error.
The execution environment has also been installed with the necessary python packages - pan-os-python and pan-os.

## Current behavior
Error message from console, please see below.
~~~
{
  "msg": "Missing required library \"pan-os-python\".",
  "invocation": {
    "module_args": {
      "provider": {
        "ip_address": "x.x.x.x",
        "username": "xxx",
        "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
        "port": 443,
        "api_key": null,
        "serial_number": null
      },
      "name": "TCP_111",
      "protocol": "tcp",
      "destination_port": "111",
      "description": "TCP port 111",
      "vsys": null,
      "commit": false,
      "username": "xxx",
      "port": 443,
      "state": "present",
      "device_group": "shared",
      "ip_address": null,
      "password": null,
      "api_key": null,
      "source_port": null,
      "tag": null
    }
  },
  "_ansible_no_log": false,
  "changed": false,
  "item": {
    "key": "TCP_111",
    "value": {
      "name": "TCP_111",
      "port": "111",
      "protocol": "TCP"
    }
  },
  "ansible_loop_var": "item",
  "_ansible_item_label": {
    "key": "TCP_111",
    "value": {
      "name": "TCP_111",
      "port": "111",
      "protocol": "TCP"
    }
  }
}

~~~

## Possible solution
Could it be that the paloaltonetworks.panos collections is unable to access the python packages installed via `pip install` in the container? Are there any specific steps to take to set up the python modules in the new AAP2.2 execution environment.

## Context
I am trying to use a simple playbook to create a new panos service object in my paloalto.

- Collection:
~~~
bash-4.4# bash-4.4# ansible-galaxy collection list

# /usr/share/ansible/collections/ansible_collections
Collection             Version
---------------------- -------
ansible.netcommon      3.0.1
ansible.posix          1.4.0
ansible.utils          2.6.1
ansible.windows        1.10.0
check_point.mgmt       3.1.0
community.crypto       2.4.0
community.general      5.3.0
community.network      4.0.1
community.windows      1.10.0
paloaltonetworks.panos 2.9.0
~~~
- Python: Python 3.8.13
- Ansible:  2.12.5
- PAN-OS Python Library & version (e.g. pandevice 0.14.0, pan-os-python 1.0.2): pan-os-python==1.5.1

**Comment by shinmog** [comment]
Seems like the container doesn't have pan-os-python installed in it.

I'm going to enhance the checks for the next release to show a bit more information about what's being checked and where to help debug some of these environment issues.

**Comment by david-johnstone** [comment]
Currently running Ansible Automation Platform AAP 2.2 which uses podman containers to execute templates and still receiving the same error despite having pan-os-python being installed in the container. Using latest collection from Galaxy paloaltonetworks-panos-3.0.0

Container Details:

**# requirements.txt**
psutil
pandevice==0.14.0
certifi
chardet==3.0.4
idna==2.8
pan-os-python
pan-python
requests==2.22.0
urllib3==1.25.11
xmltodict==0.12.0
openpyxl
selinux

**# requirements.yml**
---
collections:
  - paloaltonetworks.panos
  - community.general

**Error from Ansible Automation Platform Console:**

{
  "pypi": "https://pypi.org/project/pan-python",
  "syspath": [
    "/tmp/ansible_panos_object_facts_payload_164rchcs/ansible_panos_object_facts_payload.zip",
    "/usr/lib64/python36.zip",
    "/usr/lib64/python3.6",
    "/usr/lib64/python3.6/lib-dynload",
    "/usr/lib64/python3.6/site-packages",
    "/usr/lib/python3.6/site-packages"
  ],
  "msg": "Missing required library \"pan-python\".",

**Container pan-os-python Details**

Downloading https://galaxy.ansible.com/download/paloaltonetworks-panos-3.0.0.tar.gz to /home/runner/.ansible/tmp/ansible-local-1v3483z7d/tmpwwp4fwrg/paloaltonetworks-panos-3.0.0-xk3y1ej6
Installing 'paloaltonetworks.panos:3.0.0' to '/usr/share/ansible/collections/ansible_collections/paloaltonetworks/panos'
paloaltonetworks.panos:3.0.0 was installed successfully

**Task Object**
panos_object_facts
