### ISSUE TITLE
Inaccurate Documentation

### ISSUE THREAD

**Issue by RyanMBess** [PaloAltoNetworks/pan-os-ansible#343]
Please update the galaxy site so that it has a requirements section much like Cisco ISE does.  Currently on the galaxy site it just lists the collection.

https://galaxy.ansible.com/cisco/ise

Requirements
Ansible >= 2.9
[Cisco ISE SDK](https://github.com/CiscoISE/ciscoisesdk) v1.4.0 or newer
Python >= 3.6, as the Cisco ISE SDK doesn't support Python version 2.x
requests >= 2.25.1, for the personas modules and personas_deployment role.
Install
Ansible must be installed ([Install guide](https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html))

sudo pip install ansible
Cisco ISE SDK must be installed

sudo pip install ciscoisesdk
Install the collection ([Galaxy link](https://galaxy.ansible.com/cisco/ise))

ansible-galaxy collection install cisco.ise

**Comment by shinmog** [comment]
Seems you've accidentally opened this issue against the wrong repo.  You want this repo:  https://github.com/CiscoISE/ansible-ise
