### ISSUE TITLE
Get Palo Alto Tags via Ansible

### ISSUE THREAD

**Issue by RyanMBess** [PaloAltoNetworks/pan-os-ansible#344]
I need to query data within the palo and compare it to data within the CMDB and do some reconciliation based upon the results.  
https://ansible-pan.readthedocs.io/en/latest/modules/panos_object_facts_module.html 

    - name: Find all tags
      paloaltonetworks.panos.panos_object_facts:
        provider: '{{ device }}'
        name_regex: '*'
        object_type: 'tag'

This results in the below.  What is the msg trying to tell me here?  There is nothing in the link above that states this is deprecated.   

fatal: [palo.lab.local]: FAILED! => {"changed": false, "deprecations": [{"collection_name": "paloaltonetworks.panos", "msg": "Deprecated; use object specific modules instead", "version": "3.0.0"}], "msg": "Invalid regex: nothing to repeat at position 0"}

Further there's nothing in the link that shows what are required attributes.  So if you run the below i would assume it would return all tags
    - name: Find all tags
      paloaltonetworks.panos.panos_object_facts:
        provider: '{{ device }}'
        object_type: 'tag'

but it just errors out with the below.
fatal: [palo.lab.local]: FAILED! => {"changed": false, "msg": "one of the following is required: name, name_regex, field"}

**Comment by shinmog** [comment]
Ok, so we've updated the `panos_tag_object` resource in 2.12.0 to be a network resource module style, so you can use it instead of `panos_object_facts`, which is deprecated.  To get all objects, you can use `gathered_filter`, as is standard in network resource modules, like so:

```yaml
- name: Get all tags
  panos_tag_object:
    provider: '{{ device }}'
    state: 'gathered'
    gathered_filter: '*'
```

With regards to this issue, however, if you want to be using `panos_object_facts` then `*` is not a valid regex, which is why you're getting that error.  You probably meant to do `.*`.

**Comment by RyanMBess** [comment]
Can you provide me the link to where this is documented?

**Comment by shinmog** [comment]
The module is documented like all the other modules, here's the documentation for it:

https://paloaltonetworks.github.io/pan-os-ansible/modules/panos_tag_object_module.html

Additionally, there is a whole guide devoted to learning and utilizing `gathered_filter` here:

https://paloaltonetworks.github.io/pan-os-ansible/gatheredfilter.html

Just to restate it, the param `gathered_filter` within `panos_tag_object` only exists in 2.12.0 that I just released.

If you're asking about the regex tho with regards to the error you saw, you can just use python and get the exact same error you saw when you tried to run the `panos_object_facts` module:

```python
# Raises the same error mentioned in comment 0
import re
re.search('*', 'github issue 344')

# Works ok
re.search('.*', 'github issue 344')
```

**Comment by RyanMBess** [comment]
Thank you.  I believe part of the problem is the headings on the modules

As an example: https://paloaltonetworks.github.io/pan-os-ansible/modules/panos_tag_object_module.html 

The heading states paloaltonetworks.panos.panos_tag_object module – **Create** tag objects on PAN-OS devices

Because of the heading i skipped this module and tried to find something else that would work.  Then when it error'd it did tell me it was depreciated but didn't help point me to this module.  I will look more closely next time but do feel the headings could be better worded so these modules are easier to find and use.


Another example in this same module is i see the "STATE" has alot more options.  Where can i read / see examples of each of the staes and what their use case are.  Example, when would i use "merged" or deleted or replaced.

**Comment by shinmog** [comment]
Hrm..  Well, back in the day, that heading was accurate.  But now, if a module supports the network resource module states, then it's not just creating.  Especially since `gathered_filter` exists now, it's not even tied to a single object anymore.  I've just opened #345 so you can follow that if you want to see when the module docs stop saying "Create".

As for the states, these are covered by Ansible's documentation:

https://docs.ansible.com/ansible/latest/network/user_guide/network_resource_modules.html

I know I've seen better examples on Ansible's website for what the network resource module states mean, but that was the first thing I found.

**Comment by shinmog** [comment]
Besides the NRM states, there's also "absent" and "present".  These are the old states that regular Ansible modules supported and mean exactly what they say.

`absent` - Make sure this thing does not exist
`present` - Make sure it exists and looks exactly how I've defined in this YAML definition passed in to this module

`absent` is the same as `removed`, while `present` is the same as `replaced`.  All the other states are new and are defined as above.

**Comment by RyanMBess** [comment]
Thanks for the NRM link, i'm sure other would appreciate the link if it were added to the state attribute site so others can reference.  

Appreciate your time as i've been taped to automate our FW's with Ansible.  It's hard enough as it is even with these modules.  Lots to think about.

**Comment by RyanMBess** [comment]
Sorry few more questions that i can not find links to.
1. You had mentioned that 2.12.0 is the latest, why do i see a 3.0.0 listed and where can i find out what is new in 3.0?  
2. Which version should i start with?  
3. Which Palo Alto Firmware versions were each of these modules tested against.

**Comment by shinmog** [comment]
1. Don't use v3.0.0, it's older.  I've been asking RedHat to remove that version for months and it's still there.  v3.0.0 will eventually be a legitimate release that people should use, but for right now don't use it.  It is essentially v2.10.0 I think..?  So it's a few months old at this point.
2. Always use the most recent, so v2.12.0 as of today
3. Most modules are PAN-OS v6.1 and onwards.  If a particular module requires a higher version of PAN-OS, it will (hopefully) say as much in the docs but the module itself double checks you're meeting min PAN-OS version requirements.

**Comment by RyanMBess** [comment]
I built a new execution enrionment with the 2.12.0 version installed.  Then i used your code 
- name: Get all tags
  panos_tag_object:
    provider: '{{ device }}'
    state: 'gathered'
    gathered_filter: '*'

ansible-runner run -p local/compare_tags.yaml --inventory local/zhosts --container-image=localhost/palo_ee_v2.12 .


results in : fatal: [pan.lab.local]: FAILED! => {"changed": false, "msg": "missing required arguments: name"}

Below is showing the collections installed on this Execution Envrionment.  
ryan@ANSIBLE-ISE:~/ee/palo_ee/palo_ee_v2.12$ podman run --rm localhost/palo_ee_v2.12:latest ansible-galaxy collection list

# /usr/share/ansible/collections/ansible_collections
Collection             Version
---------------------- -------
paloaltonetworks.panos 2.12.0 


Thoughts?

**Comment by RyanMBess** [comment]
Ignore the previous comment.  It works.  I needed to run it with ansible-navigator and then reference the new EE.
