### ISSUE TITLE
RBAC Documentation

### ISSUE THREAD

**Issue by ai-ryanbess** [PaloAltoNetworks/pan-os-ansible#357]
In keeping with best practices we are striving to keep the account used for Ansible to interact with the FW to only what it needs.  Is there any documents that outline what perms each of the modules need to complete the task?  For example, https://paloaltonetworks.github.io/pan-os-ansible/modules/panos_check_module.html what would we need to delegate to the account for the panos_check_module to work?

**Comment by jamesholland-uk** [comment]
Hi @ai-ryanbess, the Collection uses the XML API under the hood, the RBAC options for which are:
- Report
- Log
- Configuration
- Operational Requests
- Commit
- User-ID Agent
- Export
- Import
`panos_check` uses operational requests to check the status of the device. Other examples of op commands include `panos_software`. The vast majority of the modules are CRUD for configuration, but there examples of modules using import, export, commit, log, etc too.

**Comment by jamesholland-uk** [comment]
Hi @ai-ryanbess, I published [this](https://pan.dev/ansible/docs/panos/info/pan-os-rbac) to describe the theory of RBAC when using Ansible for PAN-OS, does that work for you?
