### ISSUE TITLE
security_role parameter commit default incorrectly stated as no

### ISSUE THREAD

**Issue by themistymay** [PaloAltoNetworks/pan-os-ansible#41]
## Documentation link

https://ansible-pan.readthedocs.io/en/latest/modules/panos_security_rule_module.html

## Describe the problem

Incorrectly states default of `commit` is **no**, reality is the default is **yes**

## Suggested fix

Documented default of **no** seems more sane. Change code to reflect documented default.

**Comment by mrichardson03** [comment]
Will be fixed with #35.
