### ISSUE TITLE
panos_log_forwarding_profile_match_list log_type 'decryption' isn't accepted

### ISSUE THREAD

**Issue by rcaneca-salt** [PaloAltoNetworks/pan-os-ansible#414]
## Describe the bug

There is one choice missing in the log_type from the panos_log_forwarding_profile_match_list module.

## Expected behavior

I should be able to configure a Log Forwarding Profile Match List with the Log Type 'decryption'.

## Current behavior

I'm using the panos_log_forwarding_profile_match_list module and the Log Type 'decryption' is not valid.

## Possible solution
From the panos_log_forwarding_profile_match_list.py file the valid choices are traffic, threat, wildfire, url, data, gtp, tunnel, auth, sctp.
The choice decryption should also be added to the available choices.

## Steps to reproduce

- name: Log Forwarding Profile Test
  paloaltonetworks.panos.panos_log_forwarding_profile:
    provider: '{{ palo_provider }}'
    name: 'Profile'
    state: 'present'

- name: Test log_type='decryption'
  paloaltonetworks.panos.panos_log_forwarding_profile_match_list:
    provider: "{{ palo_provider }}"
    log_forwarding_profile: 'Profile'
    name: 'match_list'
    log_type: 'decryption'
    state: 'present

## Context
Currently can't use this ansible module to create a match-list with the type 'decryption'. 
I have to either do it manually or use the config module.

## Your Environment

- Collection: paloaltonetworks.panos 2.13.2 
- Python: Python 3.11.1
- Ansible: ansible [core 2.14.3]
- PAN-OS Python Library & version : pan-python 0.17.0 ; pandevice 0.14.0

**Comment by rcaneca-salt** [comment]
Screenshot with from the GUI with the valid log types:
![image](https://user-images.githubusercontent.com/127232903/230385493-2735b29e-4384-4e7b-9ac0-05391fb46866.png)

**Comment by jamesholland-uk** [comment]
[Decryption logs were added in PAN-OS 10.0](https://docs.paloaltonetworks.com/pan-os/10-0/pan-os-new-features/decryption-features/enhanced-ssl-decryption-troubleshooting), we'll need an enhancement to the module to get this one working for you
