### ISSUE TITLE
Commit by particular user in panos modules 

### ISSUE THREAD

**Issue by sikulkar** [PaloAltoNetworks/pan-os-ansible#42]
### Is your feature request related to a problem?

While using any of the PAN-OS modules, it includes commit -all option by default if any configuration is changed. However, in our production Panorama, many of the team members are working with their individual unsaved changes. Commit-all is not very helpful and might be dangerous if changes from other members get commited and pushed.

### Describe the solution you'd like
All the PAN-OS modules should commit changes made by the user rather than commit all

Modules should include an option of making partial changes/ changes made by user only / commit all changes

### Describe alternatives you've considered

Making use of panos_commit module

**Comment by mrichardson03** [comment]
Removing of the per-module commit param is being started in #35.

**Comment by stealthllama** [comment]
Unless I am mistaken, I believe the original concern was that commit-all pushes are performed whenever the panos_commit module is called and that they should be a separate function.  This behavior is planned for a future release.

**Comment by Sunny19919** [comment]
Was it fixed ? As I am new and facing this issue even when I specify one admin it is pushing changes for all templates devices groups everthing
