### ISSUE TITLE
panos_aggregate_interface - no option for Fast Failover

### ISSUE THREAD

**Issue by antoinekh** [PaloAltoNetworks/pan-os-ansible#422]
## Describe the bug

There is no option to enable Fast Failover with ansible.

Only these option are available for lacp:
 - lacp_enable
 - lacp_passive_pre_negotiation
 - lacp_rate
 - lacp_mode

## Screenshots

![image](https://user-images.githubusercontent.com/52744345/232518682-220b882a-43c7-4e0c-8b1b-1c5c8e115fda.png)

## Possible solution

Add an option to enable the feature

## Your Environment

Collection: paloaltonetworks.panos 2.13.2
Python: 3.6.8
Ansible: 2.10.17

**Comment by jamesholland-uk** [comment]
Thanks for raising this one @antoinekh, we should be able to get this for you in the next releases of the Ansible collection and the required pan-os-python package
