### ISSUE TITLE
Cannot use panos_security_rule using a Private IP in the device variables(only this module)

### ISSUE THREAD

**Issue by fersherlsgithub** [PaloAltoNetworks/pan-os-ansible#431]
## Describe the bug

I noticed something really interesting when using the **panos_security_rule** module

For some reason, When I try to configure rules in a Palo Alto VM-500 using the Public IP of the mgmt Interface, it works like a charm configures everything as expected.

But If I use a private IP(Same palo alto interface just using the private IP), only the panos_security_rules does not work, it just hangs for a while and throws the following error.

**An exception occurred during task execution. To see the full traceback, use -vvv. The error was: http.client.RemoteDisconnected: Remote end closed connection without response**

Any other playbooks module like for example create_objects, custom_urls, etc. works with the private IP, So I pretty much rule out a network/connectivity/authentication issue with that.

## Expected behavior

I think it should work normally with Private IP

## Current behavior

It does not apply the changes only for that specific module

## Possible solution

I was doing a little research since I dont have a good DEV background but it could be something related to the base.py file not gathering the correct data

## Steps to reproduce

1. Use a private IP in the device var
2. Try to apply the panos_security_rule
3. Hangs

## Context

Was trying to configure a Palo Alto using the private IPs for enchanced security

## Your Environment

STAGE

- Collection: paloaltonetworks.panos 2.13.0
- Python: 3.8.10
- Ansible:  core 2.13.7
- PAN-OS Python Library & version (e.g. pandevice 0.14.0, pan-os-python 1.0.2):
pan-os-python 1.7.3
pandevice 0.14.0
pan-python 0.17.0

**Comment by jamesholland-uk** [comment]
Hi @fersherlsgithub, can you share the playbook code (sanitized as appropriate) and run ansible with -vvv to get some verbose output. Also, what differences are there in the path between using the private IP and the public IP in terms of routing, NAT, middleboxes, etc?

**Comment by fersherlsgithub** [comment]
Hey James

Thanks for replying!

The difference in the Path when Im using a private IP, is that Im connected to a VPN which I allow access to the same firewall, or any other I need to configure, so this is kept internally.

Path wise should be the same since either if public or private IP in the Palo alto its the same mgmt interface(Public IP is NAT to the private IP Im using). I ruled out this myself(connectivity/authentication/network) just because it works with other playbooks just this one is giving me this error.(Other playbooks are configured the same for the "device" part)

Here's how my playbooks look, Im using a "Main" playbook in which I call other playbooks, in my variables file is where I state either a Public IP or private IP for variable "Firewall-IP".

In the playbook "create_fw_rules.yml" I actually got many rules but just kept one.

To add some weirdness to it, if I lets say add a new rule, using the public IP, it adds it without issues, if I try to do that with private IP, it hangs, BUT, if I first configure the rule with a public IP, and theeeen change the IP to the private, it will let me actually modify the new created rule, so its just a matter of when I try to add new rules. its weird.


[output.txt](https://github.com/PaloAltoNetworks/pan-os-ansible/files/11401489/output.txt)

**Comment by fersherlsgithub** [comment]
No worries @jamesholland-uk , yeah the Firewall-ip should be firewall-ip, and the source_ip its also correct on my actual playbook, this is just sanitization typos.

I got 10.2.4 on my FWs already but this happened since 10.1.0 so I dont think the fw Version is an issue.

I have python 3.8.10 not sure if that could be a problem, Collection I agree its also not a problem since I played already with a lot of collection version with the same issue. so the difference in version is 

panos-os-python 1.11.0 I have 1.7.3

Ill try to upgrade to those version to see if it makes any difference

Just as a question, you can Use a private IP, and Public IP, without any kind of issues when you add a new ACL line?

Best regards!

**Comment by jamesholland-uk** [comment]
Hi @fersherlsgithub 
> Just as a question, you can Use a private IP, and Public IP, without any kind of issues when you add a new ACL line?
I don't have a network topology where I can reach the same firewall management interface with both private and public/NAT IP addresses. However, I do testing against firewalls in my local network (private IP) and virtual firewalls in public cloud (public/NAT IP) and have never seen the behaviour describe in this issue.

**Comment by jamesholland-uk** [comment]
Without a way to replicate this problem, there is no way to investigate further. If a way to replicate this problem is found, please reopen this issue
