### ISSUE TITLE
panos_loadcfg: Export config module

### ISSUE THREAD

**Issue by pleegor** [PaloAltoNetworks/pan-os-ansible#44]
Hi, 

While reading documentation, I saw there is import parameter that allows to import previously offloaded config. I am wondering if there is export parameter that will allow to export config files.

**Comment by mrichardson03** [comment]
This would be resolved by #53.

**Comment by rjithu** [comment]
I have a write-up on this you can find it in the below link. 
https://github.com/rjithu/Export-Palo-Alto-Configuration-in-SET-Json-AND-XML-FORMAT-using-automated-scripts
