### ISSUE TITLE
syspath being used instead of ansible_python_interpreter - missing required library

### ISSUE THREAD

**Issue by coolcps** [PaloAltoNetworks/pan-os-ansible#440]
Similar to issue #337, but not using AAP.  For some reason only this syspath variable is being looked at, even if I put the ansible_python_interpreter var in the playbook call with -e 'anisble_python_interpreter=home/chris/ansible/venv/bin/python'.  The pan-python module is installed in the 3.10 python in my venv, but not in the 3.6 that is in the syspath that somehow ansible is picking up only attempting to run this collection.

`ansible [core 2.11.6] 
  config file = home/chris/ansible/ansible.cfg
  configured module search path = ['/home/chris/ansible/$NAPALMMODULES']
  ansible python module location = /home/chris/ansible/venv/lib/python3.10/site-packages/ansible
  ansible collection location = /home/chris/.ansible/collections:/usr/share/ansible/collections
  executable location =/home/chris/ansible/venv/bin/ansible
  python version = 3.10.8 (main, Nov 11 2022, 23:09:52) [GCC 8.5.0 20210514 (Red Hat 8.5.0-4)]
  jinja version = 3.0.3
  libyaml = True
`

`TASK [Backup device config (primary)] ***************************************************************************************************************************************************************************************************************
fatal: [lab-ent-nfw]: FAILED! => {"changed": false, "msg": "Missing required library \"pan-python\".", "pypi": "https://pypi.org/project/pan-python", "syspath": ["/tmp/ansible_paloaltonetworks.panos.panos_op_payload_tozslpny/ansible_paloaltonetworks.panos.panos_op_payload.zip", "/usr/lib64/python36.zip", "/usr/lib64/python3.6", "/usr/lib64/python3.6/lib-dynload", "/usr/local/lib/python3.6/site-packages", "/usr/lib64/python3.6/site-packages", "/usr/lib/python3.6/site-packages"]}

`

**Comment by setswei** [comment]
I am also running into this issue with my pan playbooks. Does anyone have a fix or work around ?

**Comment by jamesholland-uk** [comment]
Hi folks, have you tried using either of these options in your ansible.cfg?
https://docs.ansible.com/ansible/latest/reference_appendices/config.html#collections-paths
https://docs.ansible.com/ansible/latest/reference_appendices/config.html#collections-scan-sys-path

**Comment by jamesholland-uk** [comment]
Does it help to put `ansible_python_interpreter: "{{ ansible_playbook_python }}"` in the `all.yml` file within the `group_vars` directory?
With that line, Ansible's runtime output of python was as expected, without that line, it picked up the system default python.

Tested using these tasks:
```
    - name: show python lib/site paths
      python_requirements_info:
      register: pyinfo

    - name: Display Python Info 
      ansible.builtin.debug:
        msg: '{{ pyinfo.python }}'
```

Without that line:
`/opt/homebrew/opt/python@3.11/bin/python3.11`
With that line:
`/Users/jholland/.pyenv/versions/3.10.4/bin/python`

Hope that helps

**Comment by coolcps** [comment]
Defining the interpreter in all.yml works.  So it looks like in ansible.cfg the “interpreter_python” var works, but “ansible_python_interpreter” does nothing.  Not sure the root of the issue, but using the other variable will work for me.  Thanks for putting me on the right track!

**Comment by jamesholland-uk** [comment]
Thanks for the feedback @coolcps. Are we good to close this issue?

**Comment by jamesholland-uk** [comment]
(FYI, on root cause, it could be due to the boilerplate code that is required for Ansible certification around [absolute imports](https://docs.ansible.com/ansible/latest/dev_guide/testing/sanity/future-import-boilerplate.html))?

**Comment by coolcps** [comment]
Yes I think so, seems like may be more of an issue with the ansible.cfg documentation more than anything else.

**Comment by jamesholland-uk** [comment]
Thanks :-)
