### ISSUE TITLE
panos commit doesn't commit to multiple device groups at once

### ISSUE THREAD

**Issue by sikulkar** [PaloAltoNetworks/pan-os-ansible#52]
## Describe the bug

Compared to the Panorama GUI commit-all , the panos_commit module does NOT push the changes to multiple device groups at once/in parallel

## Expected behavior

The panos_commit module should allow the changes to be pushed to multiple device groups at once/ in parallel fashion.

## Current behavior

Currently, the panos_commit module supports single device group at a time and if used with loop functionality, makes the pushes to the device groups in serial fashion

## Possible solution

- Allow parallel push for device groups 
- Data type of device_group as list 

## Steps to reproduce

We have more than 1 device group in our environment and would like to push changes to all of the device groups at once/in parallel -> Similar to what we do in GUI

I have provided an example where I have more than 1 device group and using the loop functionality 
device_group_list: ['device_group_1', 'device_group_2', 'device_group_3']

    - name: Commit changes on Panorama and push to Device Groups
      panos_commit:
        ip_address: "{{ panorama_ip }}"
        username: "{{ username }}"
        password: "{{ password}}"
        admins: ['admin']
        device_group: "{{ item }}"
      loop: "{{ device_group_list }}"
      loop_control:
        loop_var: item

      register: commit_output

## Context

My ansible playbook is part of an end to end flow to automate security policy creation. However, with more number of device groups, the automation is going to take more time to just to complete the push process to all the device groups which will increase the overall execution time of the end to end flow involving different systems. I am expecting to reduce this implementation time.
 

## Your Environment

- Version used: Palo Alto galaxy Module - 2.4.1
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): Ansible Tower and Ansible version - 2.9.5
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by stealthllama** [comment]
The new `panos_commit_panorama` module will allow you to commit the candidate configuration of multiple device groups.  However, the new `panos_commit_push` module will still only allow config pushes to a single device group.  This is a limitation of the underlying XML API.  You can use an Ansible `loop` and `sync=False` to emulate the native `commit-all` behavior.

**Comment by achoudh5** [comment]
@stealthllama I cannot find the modules you mentioned. I am using `panos_commit` and getting this error:-

`"msg": "Failed commit-all: Commit failed"`

My task look something like:-

```
        - name: commit changes by specified admins to firewall
          panos_commit:
            provider: "{{ panorama_provider }}"
            device_group: '{{ Device }}'
```

Runnning using:- ` ansible-playbook -e 'Device=<device_name>' auto.yaml `

**Comment by ummerishtiaq** [comment]
Hi there, i am also facing the same issue and I did use sync=False, and also tried async_status to get the status, however, in the Panorama, it is creating a separate commit job for each entry, its like 10 entries in the loop, all are executing separately and concurrently. So using this technique, in Panorama, maybe first 4 entries are in progress but others are in Active queue, awaiting the previous entries to get completed. Its actually not a replacement of Panorama Commit-All, its just executing all commits separately and concurrently.

![Screenshot 2023-01-13 175223](https://user-images.githubusercontent.com/12776803/212324548-972297b0-6f27-4933-8dac-e4434f4fe5dc.png)

Is there a way, that is still there for an actual replacement of commit-all?

**Comment by jamesholland-uk** [comment]
@ummerishtiaq Today, the panos_commit_push module takes a single DG (a string, the name of the DG) as a parameter, so loop is the best option.
In order to accept a list of DGs, that parameter would need to become a list of strings instead of a single string. That would be a breaking change for everyone using the module today.
