### ISSUE TITLE
Panorama: Option to Retrieve license keys from license server

### ISSUE THREAD

**Issue by cindyteng** [PaloAltoNetworks/pan-os-ansible#54]
### Is your feature request related to a problem?

I have a requested functionality for the playbook where the license to be configured will come from the option "retrieve license keys from license server"

### Describe the solution you'd like
Add this option aside from using **authcode** from **panos_lic.py** or **uploading** a license key from **panos_import.py**.

### Describe alternatives you've considered
Request a different functionality from client in selecting/input of license.

### Additional context
I am stuck in finding right module to implement this.

Thank you very much.

**Comment by mrichardson03** [comment]
The `panos_lic` module will fetch the license keys from the licensing server when `authcode` is not specified as an argument.

**Comment by cindyteng** [comment]
Thank you very much for your email.
