### ISSUE TITLE
Request to Add Module for Configuring Dashboard Widgets

### ISSUE THREAD

**Issue by cindyteng** [PaloAltoNetworks/pan-os-ansible#57]
### Is your feature request related to a problem?
I did not see any dashboard widgets related requests so far.

### Describe the solution you'd like
A request to add a module/functionality where we can add desired widget for the dashboard.
"You can also decide which **widgets to display** or hide so that you see only those you want to monitor."
- https://docs.paloaltonetworks.com/pan-os/9-0/pan-os-web-interface-help/dashboard/dashboard-widgets

### Describe alternatives you've considered

None so far.

### Additional context

This task on my playbook is on hold and pending. Hoping for your help on this.

Thank you very much for your support.

**Comment by mrichardson03** [comment]
This doesn't appear to be supported by the API, or represented by a configuration change on the device, so it doesn't look like this can be done via a module.

**Comment by cindyteng** [comment]
Thanks for the reply.
Oh as expected, I also checked the api documentation and wasn't able to
find widget.
