### ISSUE TITLE
paloaltonetworks.panos.panos_static_route on 2.21.2

### ISSUE THREAD

**Issue by patsilvafox** [PaloAltoNetworks/pan-os-ansible#584]
## Describe the bug
while creating a static route that has the nexthop_type as 'none' the playbook fails that the an empty value on nexthop is not allowed. Further the documentation seems also misleading, as it says: "Next hop IP address. Required if state=present." This shouldn't be the case for nexthop_type: 'none'.

## Expected behavior
On version 2.20.0 it works as expected.

## Current behavior
Error: Failed create:  to_Users_10.14.27.248_29 -> nexthop is invalid"

## Possible solution
Enforcing the 2.20 collection get it back to a working state.

## Steps to reproduce
Task:
      paloaltonetworks.panos.panos_static_route:
        provider: '{{ provider }}'
        template: '{{ template_name }}'
        virtual_router: '{{ vr_router_datacenter }}'
        name: 'to_Users_{{ route_name }}'
        destination: '{{ user_network }}'
        interface: '{{ int_tunnel }}'
        nexthop_type: 'none

1.
2.
3.
4.

## Your Environment

- Collection: 2.21.2
- Python:
- Ansible:
- PAN-OS Python Library & version (e.g. pandevice 0.14.0, pan-os-python 1.0.2):

**Comment by alperenkose** [comment]
We have a [draft PR](https://github.com/PaloAltoNetworks/pan-os-ansible/pull/587) that will resolve this issue however it depends on a change in pan-os-python. We need to wait for pan-os-python PR to be merged before merging this.

**Comment by alperenkose** [comment]
This has been fixed in currently released version `2.21.3`.
