### ISSUE TITLE
panos_op Pipe through a command

### ISSUE THREAD

**Issue by fallenfuzz** [PaloAltoNetworks/pan-os-ansible#61]
Hi,

Tries the panos_op module and found that can't do anything with '|'.
Am I doing something wrong or that one really missing?

ansible 2.9.8
using collection

Thanks

**Comment by mrichardson03** [comment]
You'll have to be more specific.  You certainly can pipe the output to other filters:

```
    - panos_op:
        provider: '{{ device }}'
        cmd: 'show interface ethernet1/1'
      register: result

    - debug: var=result

    - debug:
        msg: "{{ result.stdout | from_json | json_query('response.result.hw.mac')  }}"
```
