### ISSUE TITLE
Support for a Molecule Test with Drivers Docker/Vagrant

### ISSUE THREAD

**Issue by cindyteng** [PaloAltoNetworks/pan-os-ansible#69]
### Is your feature request related to a problem?
I would like to create a molecule test for my roles involving panos.
I want to run it either using docker or vagrant.

### Describe the solution you'd like
Do you have a docker image or vagrant that can be used for a molecule test just to verify if panos modules in my roles works or configures as expected?

### Describe alternatives you've considered
For now, I am planning to manually check the environment of configuration was successfully made.

### Additional context
Thank you very much.

**Comment by mrichardson03** [comment]
We can't support this currently.
