### ISSUE TITLE
Using .pem file instead of password for providers

### ISSUE THREAD

**Issue by cindyteng** [PaloAltoNetworks/pan-os-ansible#70]
### Is your feature request related to a problem?
None so far.
Hello, I am using pem files in accessing instances with Palo Alto OS.
I hope I can use this too as referrence for providers, instead of password.

### Describe the solution you'd like
I hope you can support this.

### Describe alternatives you've considered
Request credentials from instance creator (other team) using username and password.

**Comment by stealthllama** [comment]
SSH key pairs such as those used for accessing cloud instances cannot be used for API authentication.  Today, the only API authentication methods supported are username/password and API key.

These credentials should be stored in an Ansible vault (or other vault system such Hashicorp Vault, AWS KMS, etc) and referenced in your playbooks as variables.

**Comment by cindyteng** [comment]
Thank you very much for the infromation

**Comment by cindyteng** [comment]
Will use credentials instead, as adviced.
