### ISSUE TITLE
Create modules for missing object types

### ISSUE THREAD

**Issue by mrichardson03** [PaloAltoNetworks/pan-os-ansible#75]
### Is your feature request related to a problem?

There are several object types supported by [pan-os-python](https://pan-os-python.readthedocs.io/en/latest/module-objects.html) that there aren't Ansible modules for.

Currently, there aren't modules for the following objects:

- Application Filter
- Application Group
- Application Object
- Custom URL Category
- Dynamic User Group
- Region
- Schedule Object

### Describe the solution you'd like

These missing modules could be easily added using the existing backend code.  Only the top level module would need to be created for each.

The following modules should be created:

- `panos_application_filter`
- `panos_application_group`
- ~`panos_application_object`~
- ~`panos_custom_url_category`~
- `panos_dynamic_user_group`
- `panos_region`
- `panos_schedule_object`

**Comment by bvaradinov-c** [comment]
panos_custom_url_category was merged in develop branch.
