### ISSUE TITLE
Add template_is_optional flag to modules

### ISSUE THREAD

**Issue by mrichardson03** [PaloAltoNetworks/pan-os-ansible#77]
### Is your feature request related to a problem?

The flag `template_is_optional` has been added to the helper module to support resources that can be created directly on Panorama as well as in a template/template stack.   This needs to be added to additional modules.

### Describe the solution you'd like

Add `template_is_optional=True` to the following modules:

- `panos_email_profile`
- `panos_email_server`
- `panos_http_profile`
- `panos_http_profile_header`
- `panos_http_profile_param`
- `panos_http_server`
- `panos_snmp_profile`
- `panos_snmp_v2c_server`
- `panos_snmp_v3_server`
- `panos_syslog_profile`
- `panos_syslog_server`

**Comment by mrichardson03** [comment]
This is going to require changes in `pan-os-python`.

**Comment by Eric-Jckson** [comment]
This would be a valuable option for automating base panorama configuration settings.
