### ISSUE TITLE
Create layer3 subinterface  with panos_l3_subinterface

### ISSUE THREAD

**Issue by jrd57** [PaloAltoNetworks/pan-os-ansible#8]
Hi, i dont know why but i have a problem when i run my playbook the error is :

> FAILED! => {"changed": false, "msg": "Interface name does not have \".\" in it"}

my code is 
  - name: Create layer3 subinterface eth1
    panos_l3_subinterface:
      provider: '{{ provider }}'
      template: "{{ context }}_Network_Template"
      name: "ethernet1/1"
      tag: 2807
      zone_name: "{{ context }}_LAN"
      vr_name: "{{ context }}_VR"

Anyone know why ? thank you

**Comment by btorresgil** [comment]
That error is coming from the firewall. It’s telling you that when you use a VLAN you have to add that vlan to the name of the interface.  For example: `ethernet1/1.2807`

**Comment by jrd57** [comment]
nice, thank you that work now :)
